[plugins]
cutterslade-analyze = { id = "ca.cutterslade.analyze", version = "1.9.2" }

[versions]
token-version = "4.1.4"
ktor-version = "2.3.9"
jackson-version = "2.17.0"
jupiter-version = "5.10.2"
testcontainers-version = "1.19.7"
flyway-version = "10.11.0"

[libraries]
navfelles-rapids-and-rivers = { module = "com.github.navikt:rapids-and-rivers", version = "2023120410321701682379.55cc1a24d803"}
navfelles-token-client-core = { module = "no.nav.security:token-client-core", version.ref = "token-version"}
navfelles-token-validation-ktor = { module = "no.nav.security:token-validation-ktor-v2", version.ref = "token-version"}
navfelles-mock-oauth2-server = { module = "no.nav.security:mock-oauth2-server", version = "2.1.2"}

etterlatte-common = { module = "pensjon-etterlatte-libs:common", version = "2024.04.11-14.43.8568d342d19a"}

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.8.0"}

ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor-version"}
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor-version"}
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version"}
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor-version"}
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version"}
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-version"}
ktor-client-cio-jvm = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor-version"}
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor-version"}
ktor-server-metrics-micrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor-version"}
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version"}
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-version"}
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor-version"}
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version"}

ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor-version"}
ktor-server-tests = { module = "io.ktor:ktor-server-tests", version.ref = "ktor-version"}

database-hikari-cp = { module = "com.zaxxer:HikariCP", version = "5.1.0"}
database-flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway-version" }
database-flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway-version" }
database-postgresql = { module = "org.postgresql:postgresql", version = "42.7.3"}

jackson-datatypejsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-version"}
jackson-datatypejdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson-version"}
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-version"}

jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter-version"}
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter-version"}
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter-version"}

logging-slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.12"}
logging-logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.5.3"}
logging-logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version = "7.4"}

micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version = "1.12.4"}

mockk = { module = "io.mockk:mockk", version = "1.13.10"}

kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version = "5.8.1"}

testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers-version"}
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers-version"}